---
version: '2'

services:

  ontonethub:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pdnd-ontonethub
    image: teamdigitale/pdnd-ontonethub
    stdin_open: true
    tty: true
    ports:
      - 8000:8080/tcp
